language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
cache:
    directories:
        - $HOME/.m2
notifications:
  # Telegram notifications
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    # Notifies everyone who talked with the bot, so only notify bad stuff
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always